import Foundation
import Testing
@testable import Rapid

/// Adversarial input coverage for ``ChatExporter`` (issue #215).
///
/// Three encoders + a TOCTOU-guarded ``atomicWrite`` are the entire
/// public surface; this suite throws everything in the brief at each
/// of them (1000 random sessions; adversarial title/content/attachment
/// corpora; bulk-zip stress) and asserts every invariant the export
/// surface is supposed to hold.
///
/// Every iteration uses a SplitMix64-seeded RNG so a failure can be
/// replayed with the captured seed via a fixed-seed regression test.
// ``.serialized`` so the fuzz iterations (each drops a multi-KB..MB
// archive to a tmp file and shells out to /usr/bin/unzip) don't pile
// their file-descriptor / IO pressure on top of each other in the
// full parallel pool (issue #530). Fixture writes also retry on a
// transient EBADF via ``FixtureIO.write``.
@Suite("ChatExporter — fuzz", .timeLimit(.minutes(3)), .serialized)
struct ChatExporterFuzzTests {

    /// Helper: assert that `/usr/bin/unzip` is present on the runner.
    /// Codex r4 NIT: when missing, the per-test silent skips would
    /// quietly let the ZIP-interoperability gates degrade to no-ops.
    /// macOS 10.15+ ships `/usr/bin/unzip` from the base system, so
    /// a CI image without it is environment drift worth reporting.
    /// Failed `#require` here surfaces it loudly.
    private func requireUnzipBinary() throws {
        try #require(
            FileManager.default.fileExists(atPath: "/usr/bin/unzip"),
            "Required system binary /usr/bin/unzip not present — ZIP interop checks would silently no-op."
        )
    }

    // MARK: - Per-session encoder fuzz (1000 iterations)

    /// Pure-fn invariant: ``markdown(_:)`` never throws (it doesn't
    /// even have ``throws`` in its signature) and produces a String.
    /// We assert it returns SOMETHING for every input — even "" is
    /// fine — and that it never crashes the process. With 1000
    /// adversarial sessions covering every category in the brief.
    @Test("markdown(_:) survives 1000 adversarial sessions without crashing")
    func markdownNeverCrashes() {
        let baseSeed: UInt64 = 0xDEAD_BEEF_FACE_F00D
        let iterations = 1000
        for i in 0..<iterations {
            var rng = SplitMix64(seed: baseSeed &+ UInt64(i))
            let session = FuzzSessionFactory.makeSession(rng: &rng)
            let md = ChatExporter.markdown(session)
            // The renderer always emits at minimum the H1 + the stats
            // line; even an empty session produces > 0 bytes.
            #expect(!md.isEmpty,
                    "seed=\(baseSeed &+ UInt64(i)) iter=\(i) — markdown returned empty string")
            // Sanitizer pass: no control char survives (other than
            // tab + LF). The ChatTextSanitizer claim is bounded — a
            // single \u{0000} in the output would mean the sanitizer
            // missed a path.
            for scalar in md.unicodeScalars {
                let v = scalar.value
                let permitted = (v == 0x09 || v == 0x0A) || (v >= 0x20 && v != 0x7F)
                // Allow >= 0xA0 (non-control extended)
                let inExtended = v >= 0xA0
                #expect(
                    permitted || inExtended,
                    "seed=\(baseSeed &+ UInt64(i)) iter=\(i) — illegal control U+\(String(v, radix: 16)) leaked into markdown"
                )
            }
            // Sanitizer also strips bidi overrides — none should
            // appear in the output regardless of how the title /
            // content abused them.
            let bidiOverrides: Set<UInt32> = [
                0x061C, 0x200E, 0x200F,
                0x202A, 0x202B, 0x202C, 0x202D, 0x202E,
                0x2066, 0x2067, 0x2068, 0x2069,
            ]
            for s in md.unicodeScalars {
                #expect(
                    !bidiOverrides.contains(s.value),
                    "seed=\(baseSeed &+ UInt64(i)) iter=\(i) — bidi override U+\(String(s.value, radix: 16)) leaked"
                )
            }
        }
    }

    /// Round-trip invariant: ``json(_:)`` always succeeds + the
    /// decoded envelope's ``session`` equals the input session. The
    /// envelope's exact key set MUST stay locked.
    @Test("json(_:) round-trips 1000 adversarial sessions through ExportSessionV1")
    func jsonRoundTrip() throws {
        let baseSeed: UInt64 = 0xC0FF_EE00_DEAD_BEEF
        let iterations = 1000
        // Use the production decoder so Date fields with sub-second
        // precision (now generated by FuzzSessionFactory) round-trip
        // exactly — the #289 fix is contingent on encoder + decoder
        // staying in lockstep.
        let decoder = ChatExporter.jsonDecoder()
        let envelopeKeys: Set<String> = [
            "schemaVersion", "generator", "appVersion", "exportedAt", "session"
        ]
        for i in 0..<iterations {
            let seed = baseSeed &+ UInt64(i)
            var rng = SplitMix64(seed: seed)
            let session = FuzzSessionFactory.makeSession(rng: &rng)
            try captureFailure(seed: seed, iteration: i, label: "jsonRoundTrip") {
                let data = try ChatExporter.json(session)
                #expect(!data.isEmpty, "seed=\(seed) iter=\(i) — empty JSON")
                // Top-level keys are exactly the V1 contract — any
                // extra key here is a silent schema drift.
                guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    Issue.record("seed=\(seed) iter=\(i) — JSON not a top-level object")
                    return
                }
                #expect(
                    Set(obj.keys) == envelopeKeys,
                    "seed=\(seed) iter=\(i) — envelope keys drifted: \(Set(obj.keys).sorted())"
                )
                // Round-trip the envelope. The decoded session MUST
                // equal the input — every adversarial field included.
                let decoded = try decoder.decode(ExportSessionV1.self, from: data)
                #expect(
                    decoded.session == session,
                    "seed=\(seed) iter=\(i) — round-tripped session != input"
                )
            }
        }
    }

    /// Guard the round-trip fix for machinefi/rapid-desktop#289. Pre-fix,
    /// ``JSONEncoder.dateEncodingStrategy = .iso8601`` wrote whole-second
    /// timestamps and ``JSONDecoder.dateDecodingStrategy = .iso8601``
    /// parsed the same shape — a sub-second ``Date()`` was silently
    /// truncated on round-trip. The fix swapped both halves to a custom
    /// strategy backed by ``ChatExporterDateFormat`` (ISO-8601 with
    /// ``.withFractionalSeconds``). This test pins both halves of the
    /// fixed behaviour:
    ///   1. A sub-second ``Date`` round-trips byte-for-byte through
    ///      ``ChatExporter.json`` + ``ChatExporter.jsonDecoder()``.
    ///   2. A whole-second ``Date`` continues to round-trip exactly.
    ///   3. A v0.7.16 archive (fractional-less timestamps) is still
    ///      readable by the new decoder — proves the backwards-compat
    ///      branch in ``ChatExporterDateFormat.decode``.
    ///
    /// If assertion (1) or (3) ever flips back to "not equal", the
    /// fractional-precision contract has regressed; revisit
    /// ``ChatExporter.jsonEncoder()`` / ``jsonDecoder()``.
    @Test("json round-trip: sub-second precision is preserved (#289 fixed)")
    func jsonSubsecondPrecisionLoss() throws {
        // Millisecond-precision sub-second value. ``ISO8601DateFormatter``
        // with ``.withFractionalSeconds`` writes 3 decimal digits, so an
        // input that's already ms-aligned round-trips bit-for-bit. Pre-
        // fix this was dropped to ``1_700_000_000.0`` (whole seconds).
        let withSubsecond = Date(timeIntervalSince1970: 1_700_000_000.123)
        let session = ChatSession(
            id: UUID(),
            title: "subsec",
            alias: "qwen3.5-4b",
            messages: [
                ChatMessage(
                    id: UUID(),
                    role: .user,
                    content: "hi",
                    createdAt: withSubsecond
                ),
            ],
            createdAt: withSubsecond,
            updatedAt: withSubsecond
        )
        let data = try ChatExporter.json(session)
        // Sanity: the encoded blob carries the fractional component
        // verbatim — a regression that drops back to whole seconds
        // would land here before the Equatable check.
        let raw = String(data: data, encoding: .utf8) ?? ""
        #expect(raw.contains(".123"),
                "encoded JSON missing fractional-seconds component — encoder regressed")
        let decoder = ChatExporter.jsonDecoder()
        let decoded = try decoder.decode(ExportSessionV1.self, from: data)
        // POST-FIX behaviour: sub-second precision survives round-trip.
        // If this fires, #289 has regressed — re-examine
        // ChatExporterDateFormat + jsonEncoder/jsonDecoder.
        #expect(decoded.session == session,
                "sub-second Date round-trip regressed — #289 fix has unraveled")
        // Microsecond-precision input rounds to millisecond on encode
        // (ISO-8601 wire format caps at 3 decimal digits). The decoded
        // value MUST land within 1 ms of the original so the documented
        // precision contract is enforced.
        let withMicrosecond = Date(timeIntervalSince1970: 1_700_000_000.123456)
        let microSession = ChatSession(
            id: UUID(),
            title: "micro",
            alias: "qwen3.5-4b",
            messages: [ChatMessage(role: .user, content: "hi", createdAt: withMicrosecond)],
            createdAt: withMicrosecond,
            updatedAt: withMicrosecond
        )
        let microData = try ChatExporter.json(microSession)
        let microDecoded = try decoder.decode(ExportSessionV1.self, from: microData)
        let delta = abs(microDecoded.session.createdAt.timeIntervalSince(withMicrosecond))
        #expect(delta < 0.001,
                "microsecond input drifted by \(delta)s on round-trip — should be < 1 ms")
        // Whole-second control: an integer-second Date round-trips
        // exactly.
        let wholeSecond = Date(timeIntervalSince1970: 1_700_000_000)
        let session2 = ChatSession(
            id: UUID(),
            title: "whole",
            alias: "qwen3.5-4b",
            messages: [ChatMessage(role: .user, content: "hi", createdAt: wholeSecond)],
            createdAt: wholeSecond,
            updatedAt: wholeSecond
        )
        let data2 = try ChatExporter.json(session2)
        let decoded2 = try decoder.decode(ExportSessionV1.self, from: data2)
        #expect(decoded2.session == session2)

        // Backwards-compat gate: compose a v0.7.16-shaped archive
        // (fractional-less ISO-8601 timestamps) by hand and confirm
        // the new decoder still reads it. This is the "future re-
        // import flow loads an old archive" contract.
        let legacyEnvelope = """
        {
          "appVersion" : "0.7.16",
          "exportedAt" : "2026-06-10T12:00:00Z",
          "generator" : "Rapid Desktop",
          "schemaVersion" : 1,
          "session" : {
            "alias" : "qwen3.5-4b",
            "createdAt" : "2026-06-10T12:00:00Z",
            "id" : "11111111-1111-1111-1111-111111111111",
            "isPinned" : false,
            "messages" : [
              {
                "content" : "hi",
                "createdAt" : "2026-06-10T12:00:00Z",
                "id" : "22222222-2222-2222-2222-222222222222",
                "reasoning" : "",
                "role" : "user",
                "status" : "complete"
              }
            ],
            "title" : "legacy",
            "updatedAt" : "2026-06-10T12:00:00Z"
          }
        }
        """
        let legacyData = Data(legacyEnvelope.utf8)
        let legacyDecoded = try decoder.decode(ExportSessionV1.self, from: legacyData)
        #expect(legacyDecoded.session.title == "legacy",
                "backwards-compat decoder rejected a v0.7.16-shaped archive")
        #expect(legacyDecoded.appVersion == "0.7.16")
    }

    // MARK: - Bulk ZIP

    /// Bulk-zip 25 archives × 20 random sessions (= 500 distinct
    /// adversarial sessions), then assert per archive:
    ///   * Output is non-empty + carries the EOCD magic.
    ///   * Entry count == 1 (manifest) + 2 × sessions.
    ///   * /usr/bin/unzip -t accepts every archive (no CRC errors).
    /// Smaller archives + more of them exercises the collision
    /// counter against repeated titles + the per-archive offset/CRC
    /// arithmetic in less wall time than 1000 × 1 single-session runs.
    @Test("bulkZip(_:) produces unzip-clean archives across adversarial corpora", .timeLimit(.minutes(3)))
    func bulkZipUnzipClean() throws {
        try requireUnzipBinary()
        // 25 archives × 20 sessions each — covers the same input
        // variety in less wall time than 1000 × 1, and exercises the
        // collision counter against repeated titles.
        let baseSeed: UInt64 = 0xBAD0_FACE_F00D_BEEF
        let archiveCount = 25
        let sessionsPerArchive = 20

        for a in 0..<archiveCount {
            let seed = baseSeed &+ UInt64(a)
            var rng = SplitMix64(seed: seed)
            var sessions: [ChatSession] = []
            for _ in 0..<sessionsPerArchive {
                sessions.append(
                    FuzzSessionFactory.makeSession(
                        rng: &rng,
                        maxMessages: 12,
                        maxContentBytes: 2048,
                        bulkSafe: true
                    )
                )
            }
            try captureFailure(seed: seed, iteration: a, label: "bulkZipUnzipClean") {
                let data = try ChatExporter.bulkZip(sessions)
                // PKZIP local-header magic at offset 0
                let head = Array(data.prefix(4))
                #expect(head == [0x50, 0x4b, 0x03, 0x04],
                        "seed=\(seed) iter=\(a) — missing local-header magic")
                // EOCD signature in last 22 bytes
                let eocdHead = Array(data.suffix(22).prefix(4))
                #expect(eocdHead == [0x50, 0x4b, 0x05, 0x06],
                        "seed=\(seed) iter=\(a) — missing EOCD signature")
                // entry count = manifest + 2 × sessions
                let eocdBytes = Array(data.suffix(22))
                let entries = UInt16(eocdBytes[10]) | (UInt16(eocdBytes[11]) << 8)
                #expect(
                    Int(entries) == 1 + 2 * sessionsPerArchive,
                    "seed=\(seed) iter=\(a) — entry count drift: \(entries) vs expected \(1 + 2 * sessionsPerArchive)"
                )

                // Drop to a tmp file + run /usr/bin/unzip -t against
                // it. The top-of-test ``requireUnzipBinary`` already
                // guarantees the binary is present.
                let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
                    .appendingPathComponent("fuzz-bulkzip-\(seed)-\(a).zip")
                defer { try? FileManager.default.removeItem(at: tmp) }
                try FixtureIO.write(data, to: tmp)
                let proc = Process()
                proc.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
                proc.arguments = ["-tqq", tmp.path]
                let stderrPipe = Pipe()
                proc.standardError = stderrPipe
                proc.standardOutput = Pipe()
                try proc.run()
                proc.waitUntilExit()
                if proc.terminationStatus != 0 {
                    let errData = (try? stderrPipe.fileHandleForReading.readToEnd()) ?? Data()
                    let stderrText = String(data: errData, encoding: .utf8) ?? ""
                    Issue.record(
                        "seed=\(seed) iter=\(a) — /usr/bin/unzip -t failed (status=\(proc.terminationStatus)): \(stderrText)"
                    )
                }
            }
        }
    }

    /// Empty bulk: still a valid 1-entry (manifest-only) archive.
    @Test("bulkZip with 0 sessions is still a valid manifest-only archive")
    func bulkZipEmpty() throws {
        let data = try ChatExporter.bulkZip([])
        let head = Array(data.prefix(4))
        #expect(head == [0x50, 0x4b, 0x03, 0x04])
        let eocdBytes = Array(data.suffix(22))
        let entries = UInt16(eocdBytes[10]) | (UInt16(eocdBytes[11]) << 8)
        #expect(entries == 1)
    }

    /// Hostile title collision stress: 100 sessions all titled the
    /// same, plus a couple titled with path traversal. The collision
    /// counter must produce 100 distinct entry stems and the archive
    /// must still pass unzip -t.
    ///
    /// Codex r1 MAJOR closure: assert the archive's listed entry
    /// names are unique (ZIP permits duplicate names, so an entry-
    /// count check alone would pass a broken collision counter that
    /// writes 100 identical paths). We use `unzip -l` to read the
    /// central directory's listed names and assert the .md / .json
    /// entry-name sets are 100-unique.
    @Test("bulkZip 100 same-title sessions land as distinct entries — collision counter survives stress")
    func bulkZipCollisionStress() throws {
        try requireUnzipBinary()
        var sessions: [ChatSession] = []
        let titles = [
            "New chat",
            "New chat",
            "New chat",
            "../../etc/passwd",
            "  ",
            "..",
            "...",
        ]
        for i in 0..<100 {
            let title = titles[i % titles.count]
            sessions.append(ChatSession(
                title: title,
                alias: "qwen3.5-4b",
                messages: [
                    ChatMessage(role: .user, content: "hi \(i)"),
                    ChatMessage(role: .assistant, content: "yo \(i)"),
                ]
            ))
        }
        let data = try ChatExporter.bulkZip(sessions)
        // Entry count = 1 manifest + 2 × 100 sessions
        let eocdBytes = Array(data.suffix(22))
        let entries = UInt16(eocdBytes[10]) | (UInt16(eocdBytes[11]) << 8)
        #expect(entries == 201)
        // Drop to tmp + unzip -t.
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-bulkzip-collision-\(UUID().uuidString).zip")
        defer { try? FileManager.default.removeItem(at: tmp) }
        try FixtureIO.write(data, to: tmp)
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        proc.arguments = ["-tqq", tmp.path]
        try proc.run()
        proc.waitUntilExit()
        #expect(proc.terminationStatus == 0,
                "collision-stress archive failed /usr/bin/unzip -t (status=\(proc.terminationStatus))")

        // Codex r1 MAJOR: also assert the LISTED entry names are
        // unique. ZIP permits duplicate paths; the EOCD entry count
        // alone wouldn't catch a broken collision counter.
        let names = try listZipEntryNames(at: tmp)
        // 1 manifest + 100 .md + 100 .json = 201 distinct paths
        #expect(names.count == 201)
        #expect(Set(names).count == 201,
                "collision counter leaked duplicate names: \(names.count - Set(names).count) duplicates")
        let mdNames = names.filter { $0.hasSuffix(".md") }
        let jsonNames = names.filter { $0.hasSuffix(".json") && $0 != "manifest.json" }
        #expect(mdNames.count == 100)
        #expect(Set(mdNames).count == 100, "duplicate .md entry names")
        #expect(jsonNames.count == 100)
        #expect(Set(jsonNames).count == 100, "duplicate .json entry names")
    }

    /// Pull the listed entry names out of a ZIP via `unzip -l`. We
    /// parse the column-formatted output rather than re-implement a
    /// central-directory reader. Returns the file paths in archive
    /// order.
    private func listZipEntryNames(at url: URL) throws -> [String] {
        guard FileManager.default.fileExists(atPath: "/usr/bin/unzip") else {
            return []
        }
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        proc.arguments = ["-Z1", url.path]
        let stdout = Pipe()
        proc.standardOutput = stdout
        proc.standardError = Pipe()
        try proc.run()
        proc.waitUntilExit()
        let data = (try? stdout.fileHandleForReading.readToEnd()) ?? Data()
        let text = String(data: data, encoding: .utf8) ?? ""
        return text
            .split(separator: "\n", omittingEmptySubsequences: true)
            .map { String($0) }
    }

    /// ZIP-slip canary: extract a bulk archive whose sessions carry
    /// adversarial titles into a temp directory and assert no
    /// extracted path escapes the dir. The exporter sanitizes titles
    /// to a safe stem; we exercise that by actually running unzip and
    /// checking realpath.
    ///
    /// Codex r1 MAJOR closure: enumerating only ``extractDir`` after
    /// extraction is one-sided — an absolute-path entry (e.g.
    /// `/etc/passwd`) extracted by `unzip` could land OUTSIDE the dir
    /// and never be seen by the enumerator. Two extra gates:
    ///   1. Read every entry name from the central directory (`unzip
    ///      -Z1`) and reject any name that contains `..` segments or
    ///      starts with `/`.
    ///   2. Plant a canary file alongside ``extractDir`` and assert
    ///      its mtime didn't move (proving no entry resolved to that
    ///      sibling path during extraction).
    @Test("bulkZip + unzip -o: no extracted path escapes the destination directory (ZIP-slip)")
    func bulkZipNoSlip() throws {
        try requireUnzipBinary()
        let sessions: [ChatSession] = AdversarialTitles.path.map { evil in
            ChatSession(
                title: evil,
                alias: "qwen3.5-4b",
                messages: [
                    ChatMessage(role: .user, content: "a"),
                    ChatMessage(role: .assistant, content: "b"),
                ]
            )
        }
        let data = try ChatExporter.bulkZip(sessions)
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-slip-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let zipPath = dir.appendingPathComponent("archive.zip")
        try FixtureIO.write(data, to: zipPath)

        // Gate 1: central-directory name audit. The exporter's
        // ``sanitize`` strips `/` `\` plus path separators, then
        // drops leading `.` / `-`, so a valid archive's listed names
        // contain no `..` segments and no absolute-path prefix.
        let listedNames = try listZipEntryNames(at: zipPath)
        for name in listedNames {
            #expect(!name.hasPrefix("/"),
                    "ZIP-slip: absolute-path entry name in central directory: \(name)")
            // Reject any `..` path segment (would resolve above the
            // extract dir on a vulnerable extractor).
            let segments = name.split(separator: "/")
            for seg in segments {
                #expect(seg != "..",
                        "ZIP-slip: traversal segment '..' in entry name: \(name)")
            }
            // Reject backslash-flavoured Windows traversal too.
            #expect(!name.contains("\\.."),
                    "ZIP-slip: windows-style traversal in entry name: \(name)")
        }

        let extractDir = dir.appendingPathComponent("extract")
        try FileManager.default.createDirectory(at: extractDir, withIntermediateDirectories: true)

        // Gate 2: plant a canary file sibling to extractDir. If an
        // entry's path resolves to that sibling on extraction, the
        // file's contents would change.
        let canary = dir.appendingPathComponent("canary.txt")
        try "CANARY-ORIG".write(to: canary, atomically: true, encoding: .utf8)

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        proc.arguments = ["-o", zipPath.path, "-d", extractDir.path]
        proc.standardOutput = Pipe()
        proc.standardError = Pipe()
        try proc.run()
        proc.waitUntilExit()
        #expect(proc.terminationStatus == 0)

        // Canary still reads its original content.
        let canaryAfter = (try? String(contentsOf: canary, encoding: .utf8)) ?? ""
        #expect(canaryAfter == "CANARY-ORIG",
                "ZIP-slip: canary alongside extract dir was clobbered")

        // Enumerate every file under extractDir + check resolved
        // paths remain inside extractDir.
        let realRoot = (extractDir.path as NSString).resolvingSymlinksInPath
        let enumerator = FileManager.default.enumerator(atPath: extractDir.path)
        var anyExtracted = false
        while let p = enumerator?.nextObject() as? String {
            anyExtracted = true
            let full = extractDir.appendingPathComponent(p).path
            let resolved = (full as NSString).resolvingSymlinksInPath
            #expect(
                resolved.hasPrefix(realRoot),
                "ZIP-slip escape: \(resolved) escaped \(realRoot) (entry path \(p))"
            )
        }
        #expect(anyExtracted, "expected at least one extracted entry")
    }

    /// One session with a 4 MB body to verify the encoder doesn't
    /// silently corrupt offsets near the size threshold the brief
    /// flagged. Not 100 MB (that would slow CI to a crawl and is
    /// already covered by ``entryTooLarge``); 4 MB is a realistic
    /// upper bound for one chat with image data inlined.
    @Test("bulkZip handles a 4 MB session without offset corruption")
    func bulkZipLargeSingleEntry() throws {
        try requireUnzipBinary()
        let big = String(repeating: "a", count: 4 * 1024 * 1024)
        let session = ChatSession(
            title: "big-one",
            alias: "qwen3.5-4b",
            messages: [
                ChatMessage(role: .user, content: "hello"),
                ChatMessage(role: .assistant, content: big),
            ]
        )
        let data = try ChatExporter.bulkZip([session])
        let eocdBytes = Array(data.suffix(22))
        let entries = UInt16(eocdBytes[10]) | (UInt16(eocdBytes[11]) << 8)
        #expect(entries == 3) // manifest + .md + .json
        // Tmp + unzip -t
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-bigone-\(UUID().uuidString).zip")
        defer { try? FileManager.default.removeItem(at: tmp) }
        try FixtureIO.write(data, to: tmp)
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        proc.arguments = ["-tqq", tmp.path]
        try proc.run()
        proc.waitUntilExit()
        #expect(proc.terminationStatus == 0)
    }

    // MARK: - atomicWrite

    /// Happy path: write, then read the bytes back via stdlib + check
    /// the file is mode 0600 + no temp file leaks.
    @Test("atomicWrite: success leaves a 0600 file with exact bytes + no .tmp leak")
    func atomicWriteSuccess() throws {
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-atomic-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let dest = dir.appendingPathComponent("out.bin")
        var rng = SplitMix64(seed: 0xA70_E101)
        let payload = Data((0..<8192).map { _ in UInt8(rng.next() & 0xFF) })
        try ChatExporter.atomicWrite(payload, to: dest)
        let read = try Data(contentsOf: dest)
        #expect(read == payload)
        // mode == 0600
        let attrs = try FileManager.default.attributesOfItem(atPath: dest.path)
        let perms = (attrs[.posixPermissions] as? NSNumber)?.uint16Value ?? 0
        #expect(perms == 0o600, "expected 0600, got 0o\(String(perms, radix: 8))")
        // No leftover .rapid-export-* in the parent dir
        let siblings = try FileManager.default.contentsOfDirectory(atPath: dir.path)
        let leaks = siblings.filter { $0.hasPrefix(".rapid-export-") }
        #expect(leaks.isEmpty, "leaked temp files: \(leaks)")
    }

    /// Symlink at the destination pointing OUTSIDE the parent dir.
    /// The atomic rename should land OUR bytes at the destination
    /// path and NOT follow the symlink to write into the target
    /// outside our sandbox.
    @Test("atomicWrite: pre-existing symlink at destination does NOT write outside")
    func atomicWriteSymlinkSafe() throws {
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-symlink-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        // Target the attacker would like to clobber — a separate file
        // OUTSIDE the dir we're writing into.
        let attackerTarget = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-symlink-target-\(UUID().uuidString).txt")
        try "ORIGINAL".write(to: attackerTarget, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(at: attackerTarget) }
        let dest = dir.appendingPathComponent("export.bin")
        // Plant a symlink at the destination.
        try FileManager.default.createSymbolicLink(at: dest, withDestinationURL: attackerTarget)
        let payload = Data("FRESH".utf8)
        try ChatExporter.atomicWrite(payload, to: dest)
        // After the write, the dest must contain our payload (the
        // symlink is replaced by our real file via rename), and the
        // attacker's target file must still contain "ORIGINAL".
        let read = try Data(contentsOf: dest)
        #expect(read == payload)
        let attackerStill = try Data(contentsOf: attackerTarget)
        #expect(attackerStill == Data("ORIGINAL".utf8),
                "symlink followed: attacker target was overwritten with \(String(data: attackerStill, encoding: .utf8) ?? "?")")
        // lstat: dest is a regular file post-call, not a symlink.
        var st = stat()
        let rc = lstat(dest.path, &st)
        #expect(rc == 0)
        let isLink = (st.st_mode & S_IFMT) == S_IFLNK
        #expect(!isLink, "destination is still a symlink post-write")
    }

    /// Failure path: write into a directory that doesn't exist. Open
    /// fails on the temp path; no temp files should leak.
    @Test("atomicWrite: failed open does NOT leak a .tmp file in the parent dir")
    func atomicWriteFailureNoLeak() throws {
        // A non-existent parent directory triggers ``open`` failure.
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-doesnotexist-\(UUID().uuidString)")
        let dest = dir.appendingPathComponent("out.bin")
        do {
            try ChatExporter.atomicWrite(Data("a".utf8), to: dest)
            Issue.record("expected throw, got success")
        } catch {
            // Expected; check we didn't accidentally create the parent
            // or leave a temp file behind.
            #expect(!FileManager.default.fileExists(atPath: dir.path),
                    "atomic write created the missing parent dir as a side effect")
        }
    }

    /// Concurrency: 32 threads racing to write the same destination.
    /// The brief asks: TOCTOU safety + one of them lands intact + no
    /// temp files leak. ``atomicWrite`` uses ``O_EXCL`` on a per-call
    /// UUID-suffixed tmp name, then ``rename`` to the final path. Two
    /// concurrent calls don't collide on the tmp side (UUIDs differ);
    /// the rename winner is whichever thread finishes last. The
    /// surviving file must be intact bytes from SOMEONE.
    ///
    /// Codex r1 MAJOR closure:
    ///   1. Collect each task's success / thrown error so the test
    ///      reports if a regression makes most writers fail.
    ///   2. Use a start barrier (DispatchGroup) so every writer is
    ///      ready before any actually calls ``atomicWrite`` — without
    ///      it the first-spawned task could finish before the last
    ///      one even starts (no real contention).
    ///   3. Use 64 KB payloads so the write phase is non-trivial; a
    ///      tiny 1 KB payload completes in ~10 μs and the race window
    ///      degenerates.
    @Test("atomicWrite: 32 concurrent writes to the same dest leave one intact file + no tmp leak", .timeLimit(.minutes(1)))
    func atomicWriteConcurrentRace() throws {
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("fuzz-race-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let dest = dir.appendingPathComponent("out.bin")

        // 32 distinct payloads tagged with their writer index so we
        // can identify which winner survived. 64 KB so the write
        // phase actually takes measurable wall time and the race
        // window isn't degenerate (a 1 KB write finishes in ~10 μs,
        // smaller than thread-spawn latency, which lets the first
        // task complete before the last even starts).
        let payloads: [Data] = (0..<32).map { i in
            let stamp = "writer-\(i):"
            let reps = (64 * 1024) / stamp.utf8.count
            return Data(String(repeating: stamp, count: reps).utf8)
        }

        // Start barrier — every thread signals readiness, the
        // launcher waits for 32 signals, then opens the gate so all
        // 32 threads race the write-and-rename at the same time.
        let readyGroup = DispatchGroup()
        for _ in 0..<32 { readyGroup.enter() }
        let goSemaphore = DispatchSemaphore(value: 0)

        // NSLock-guarded outcomes — pthread-style mutation from each
        // worker thread is the simplest shape that's also visible
        // from the main thread after ``readyGroup.wait``.
        final class Outcomes: @unchecked Sendable {
            let lock = NSLock()
            var successes: Int = 0
            var failures: [Error] = []
        }
        let outcomes = Outcomes()

        // Codex r2 MAJOR closure: spawn dedicated NSThreads instead
        // of DispatchQueue.global() workers so a constrained CI runner
        // with a narrow global thread pool can't starve the
        // semaphore-blocked workers and deadlock until the 1-minute
        // test timeout.
        let workersDone = DispatchGroup()
        var threads: [Thread] = []
        for i in 0..<32 {
            let payload = payloads[i]
            workersDone.enter()
            let t = Thread {
                readyGroup.leave()
                goSemaphore.wait()
                do {
                    try ChatExporter.atomicWrite(payload, to: dest)
                    outcomes.lock.lock()
                    outcomes.successes += 1
                    outcomes.lock.unlock()
                } catch {
                    outcomes.lock.lock()
                    outcomes.failures.append(error)
                    outcomes.lock.unlock()
                }
                workersDone.leave()
            }
            t.name = "atomic-write-race-\(i)"
            threads.append(t)
        }
        // Start every thread first, then unblock the gate so all 32
        // race the write-and-rename simultaneously.
        for t in threads { t.start() }
        readyGroup.wait()
        for _ in 0..<32 { goSemaphore.signal() }
        workersDone.wait()

        outcomes.lock.lock()
        let successCount = outcomes.successes
        let failures = outcomes.failures
        outcomes.lock.unlock()

        // Every failed writer must surface a ``ChatExporterError`` —
        // never an undocumented type. A regression that started
        // throwing a different shape would surface here.
        for err in failures {
            guard let e = err as? ChatExporterError else {
                Issue.record("undocumented error from atomicWrite under race: \(err)")
                continue
            }
            if case .writeFailed = e {
                // expected category
            } else {
                Issue.record("unexpected ChatExporterError under race: \(e)")
            }
        }
        // ``rename`` on macOS replaces the existing target — every
        // writer's rename should succeed barring a transient EBUSY.
        // We pin > 50% succeed: a regression that serializes the
        // writers behind a mutex would still show as 32 success but
        // ordered, while a regression that broke ``O_EXCL`` and
        // turned everyone past the first into a hard failure would
        // surface here.
        #expect(successCount >= 16,
                "only \(successCount)/32 writers succeeded under race — atomicWrite may have regressed. Failures: \(failures.count)")

        // Some writer landed; the surviving bytes must equal exactly
        // one of the payloads.
        guard let final = try? Data(contentsOf: dest) else {
            Issue.record("no surviving file after race")
            return
        }
        #expect(payloads.contains(final),
                "surviving bytes don't match any writer's payload — torn write")
        // No temp leaks.
        let siblings = try FileManager.default.contentsOfDirectory(atPath: dir.path)
        let leaks = siblings.filter { $0.hasPrefix(".rapid-export-") }
        #expect(leaks.isEmpty, "leaked temp files after race: \(leaks)")
    }

    // MARK: - CRC32 vector sanity

    /// CRC32 of "" is 0x00000000; CRC32 of "123456789" is 0xCBF43926.
    /// Pin both — a future "optimisation" of the table-driven loop
    /// would re-trip these immediately.
    @Test("CRC32 reference vectors: empty + IEEE 802.3 standard")
    func crc32Vectors() {
        #expect(CRC32.checksum(Data()) == 0x00000000)
        #expect(CRC32.checksum(Data("123456789".utf8)) == 0xCBF43926)
        // 1 MiB of zero bytes: classic stress test.
        let zeros = Data(repeating: 0, count: 1 << 20)
        // Known: CRC32 of 1 MiB of zeros (IEEE) is 0xA738EA1C.
        #expect(CRC32.checksum(zeros) == 0xA738EA1C)
    }
}
